language: node_js
node_js:
  - "stable"
script:
  - npm run build
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  target-branch: master
  keep-history: true
  email: nawazishaliejaz@gmail.com
  name: Nawazish Ali
  on:
    branch: develop-simple